Repository TeamGrowTo/Team-GrowTo-Client, pull requests merged in 2022-02, with the labels that each got.

#96 Feature/request banner
  components/request/RequestBanner/index.tsx
  components/request/RequestBanner/style.ts
  public/assets/images/requestBannerBackground-mobile.png
Labels: 반응형💫, 모바일 :hamburger:

#100 Feature/requestweeklyrank
  .env
  .gitignore
  components/request/RequestWeeklyRank/Rank/index.tsx
  components/request/RequestWeeklyRank/Rank/style.ts
  components/request/RequestWeeklyRank/style.ts
  public/assets/icons/index.ts
  public/assets/icons/requestRankLine-mobile.svg
  types/lectures.type.ts
Labels: 반응형💫, 모바일 :hamburger:

#107 Feature/request current lecture
  components/request/RequestCurrentLecture/CurrentLecture/style.ts
  components/request/RequestCurrentLecture/style.ts
Labels: 반응형💫, 모바일 :hamburger:

#108 Feature/category list : categroy, navbar
  apis/lectures.api.ts
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/index.tsx
  components/category/CardBox/SmallCardBox/style.ts
  components/category/CardListContainer/index.tsx
  components/category/CardListContainer/style.ts
  components/category/Result/index.tsx
  components/category/Result/style.ts
  components/common/NavBar/LargeNavBar/style.ts
  components/common/NavBar/SmallNavBar/index.tsx
  components/main/LectureCategory/Category/index.tsx
  components/main/LectureCategory/Category/style.ts
  components/main/LectureCategory/index.tsx
  components/main/LectureCategory/style.ts
  pages/result/[id].tsx
  public/assets/icons/index.ts
  public/assets/icons/mainLectureDataIcon.svg
  public/assets/icons/mainLectureDesignIcon.svg
  public/assets/icons/mainLectureDeveloperIcon.svg
  public/assets/icons/mainLectureEtcIcon.svg
  public/assets/icons/mainLectureMarketingIcon.svg
  public/assets/icons/mainLecturePlanIcon.svg
  public/assets/icons/smallBlueArrowRight.svg
  public/assets/images/index.ts
  public/assets/images/mainLectureCategoryDataIcon.png
  public/assets/images/mainLectureCategoryDesignIcon.png
  public/assets/images/mainLectureCategoryDevelopIcon.png
  public/assets/images/mainLectureCategoryEtcIcon.png
  public/assets/images/mainLectureCategoryMarketingIcon.png
  public/assets/images/mainLectureCategoryPlanIcon.png
  types/info.type.ts
Labels: 반응형💫, 모바일 :hamburger:

#103 Feature/result notification
  components/result/MiddleNotification/style.ts
Labels: 반응형💫, 모바일 :hamburger:

#104 Feature/category and skill
  components/category/CategoryAndSkillList/CategoryList/index.tsx
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/MobileModal/index.tsx
  components/category/CategoryAndSkillList/MobileModal/style.tsx
  components/category/CategoryAndSkillList/SkillList/style.ts
  components/category/CategoryAndSkillList/index.tsx
  components/category/CategoryAndSkillList/style.ts
  components/category/MobileCategoryAndSkill/index.tsx
  components/category/MobileCategoryAndSkill/style.ts
  pages/category/index.tsx
  public/assets/icons/icCategoryLeftArrow.svg
  public/assets/icons/index.ts
  public/assets/images/index.ts
  public/assets/images/mobileCategoryTab.svg
Labels: 반응형💫, 모바일 :hamburger:

#105 Feature/result share
  components/result/ResultShareButton/index.tsx
  components/result/ResultShareButton/style.ts
  public/assets/icons/index.ts
  public/assets/icons/mobileResultShareIcon.svg
Labels: 반응형💫, 모바일 :hamburger:

#106 Feature/result card
  .env
  components/result/ProcessResult/ResultCard/Info/style.ts
  components/result/ProcessResult/ResultCard/SubInfo/style.ts
  components/result/ProcessResult/ResultCard/Tags/style.ts
  components/result/ProcessResult/ResultCard/index.tsx
  components/result/ProcessResult/ResultCard/style.ts
  components/result/ProcessResult/Slider/index.tsx
  components/result/ProcessResult/Slider/style.ts
  components/result/ProcessResult/index.tsx
  components/result/ProcessResult/style.ts
  components/result/ResultCardDot/index.tsx
  components/result/ResultCardDot/style.ts
  pages/result/[id].tsx
  public/assets/icons/index.ts
  public/assets/icons/mobileResultCardRightArrowIcon.svg
  public/assets/icons/mobileResultSliderLeftArrowIcon.svg
  public/assets/icons/mobileResultSliderLeftIcon.png
  public/assets/icons/mobileResultSliderRightArrowIcon.svg
Labels: 사소하지만중요해🧶, 반응형💫, 모바일 :hamburger:

#109 Feature/main lecture category
  components/main/LectureCategory/Category/index.tsx
  components/main/LectureCategory/Category/style.ts
Labels: style:tulip:, 사소하지만중요해🧶, 리팩토링 :rabbit:

#110 Feature/footer mobile
  components/main/Footer/style.ts
Labels: bug :bug:

#112 Feature/result question
  components/result/Question/QuestionButton/index.tsx
  components/result/Question/QuestionButton/style.ts
  components/result/Question/QuestionModal/DescriptionInput/style.ts
  components/result/Question/QuestionModal/DropdownInput/style.ts
  components/result/Question/QuestionModal/EmailInput/index.tsx
  components/result/Question/QuestionModal/InputForm/index.tsx
  components/result/Question/QuestionModal/InputForm/style.ts
  components/result/Question/QuestionModal/index.tsx
  components/result/Question/QuestionModal/style.ts
  components/result/Question/style.ts
  public/assets/icons/desktopDownArrowIcon.svg
  public/assets/icons/desktopUpArrowIcon.svg
  public/assets/icons/index.ts
  public/assets/icons/questionIcon.svg
Labels: 기능구현🎃, 리팩토링 :rabbit:

#116 Feature/result card
  components/result/ProcessResult/ResultCard/Info/style.ts
  components/result/ProcessResult/ResultCard/SubInfo/index.tsx
  components/result/ProcessResult/ResultCard/SubInfo/style.ts
  components/result/ProcessResult/ResultCard/Tags/style.ts
  components/result/ProcessResult/ResultCard/index.tsx
  components/result/ProcessResult/ResultCard/style.ts
  components/result/ProcessResult/Slider/index.tsx
  components/result/ProcessResult/Slider/style.ts
  components/result/ProcessResult/index.tsx
  components/result/ProcessResult/style.ts
  components/result/ResultCardDot/style.ts
Labels: style:tulip:, 리팩토링 :rabbit:

#118 Feature/result share
  components/result/ResultShareButton/index.tsx
  components/result/ResultShareButton/style.ts
  public/assets/icons/mobileResultShareIcon.svg
  public/assets/icons/resultShareIcon.svg
Labels: 리팩토링 :rabbit:

#119 Feature/result notification
  components/result/MiddleNotification/index.tsx
  components/result/MiddleNotification/style.ts
Labels: bug :bug:, 리팩토링 :rabbit:

#120 Feature/main banner
  components/main/Banner/index.tsx
  components/main/Banner/style.ts
  public/assets/images/index.ts
  public/assets/images/mobileMainBannerCompass.png
Labels: style:tulip:, 리팩토링 :rabbit:, 반응형💫

#122 Feature/redirect process page
  components/category/RedirectProcessButton/index.tsx
  components/category/RedirectProcessButton/style.ts
Labels: 리팩토링 :rabbit:, 반응형💫

#129 Feature/result card
  components/result/ProcessResult/ResultCard/Tags/index.tsx
  components/result/ProcessResult/ResultCard/Tags/style.ts
  components/result/ProcessResult/ResultCard/style.ts
  components/result/ProcessResult/Slider/style.ts
  components/result/ResultCardDot/style.ts
Labels: bug :bug:

#130 이슈 해결 배포
  components/request/RequestWeeklyRank/Rank/style.ts
  components/result/ProcessResult/ResultCard/Tags/index.tsx
  components/result/ProcessResult/ResultCard/Tags/style.ts
  components/result/ProcessResult/ResultCard/style.ts
  components/result/ProcessResult/Slider/style.ts
  components/result/ResultCardDot/style.ts
Labels: bug :bug:

#132 Feature/category and skill
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/index.tsx
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/style.ts
  components/category/CategoryAndSkillList/MobileModal/style.ts
Labels: bug :bug:

#135 Feature/redirect process page
  components/category/RedirectProcessButton/style.ts
Labels: bug :bug:

#137 Refactor/process issue
  components/process/CardTitle/style.ts
  components/process/Title/index.tsx
  components/process/Title/style.ts
  components/process/TypeButton/style.ts
  pages/processPrice/index.tsx
  pages/processTag/index.tsx
  pages/processTime/index.tsx
  public/assets/icons/index.ts
  public/assets/icons/loadingIconMobile.svg
  public/assets/icons/processPrev.svg
Labels: 기능구현🎃, style:tulip:, 리팩토링 :rabbit:, 이슈해결💟

#143 Feature/main review
  components/main/MainReview/Review/style.ts
Labels: 사소하지만중요해🧶, 이슈해결💟

#141 feature/mainReport
  components/main/MainReport/ReportSection/style.ts
  components/main/MainReport/index.tsx
  components/main/MainReport/style.ts
Labels: 사소하지만중요해🧶, 이슈해결💟

#138 Feature/category list
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/style.ts
  components/category/Result/style.ts
  components/category/SortingBox/index.tsx
  components/category/SortingBox/style.ts
  components/category/SortingBtn/index.tsx
  components/category/SortingBtn/style.ts
  package-lock.json
Labels: style:tulip:, 반응형💫, 모바일 :hamburger:, 이슈해결💟

#140 Feature/result share
  components/result/ResultShareButton/style.ts
  styles/colors.ts
Labels: 기능구현🎃, style:tulip:

#144 Feature/category and skill
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/style.ts
  components/category/CategoryAndSkillList/MobileModal/style.ts
  components/category/CategoryAndSkillList/SkillList/index.tsx
  components/category/CategoryAndSkillList/SkillList/style.ts
Labels: 사소하지만중요해🧶, 이슈해결💟

#146 Feature/result question
  components/result/Question/QuestionModal/DropdownInput/style.ts
  components/result/Question/QuestionModal/InputForm/style.ts
  components/result/Question/QuestionModal/QuestionReported/style.ts
  components/result/Question/QuestionModal/index.tsx
  components/result/Question/QuestionModal/style.ts
Labels: bug :bug:, 반응형💫

#147 Feature/result card
  pages/result/[id].tsx
Labels: bug :bug:, 이슈해결💟

#148 Feature/result share
  components/result/ResultShareButton/style.ts
Labels: bug :bug:

#150 3차 배포
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/style.ts
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/index.tsx
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/style.ts
  components/category/CategoryAndSkillList/MobileModal/style.ts
  components/category/CategoryAndSkillList/SkillList/index.tsx
  components/category/CategoryAndSkillList/SkillList/style.ts
  components/category/RedirectProcessButton/style.ts
  components/category/Result/style.ts
  components/category/SortingBox/index.tsx
  components/category/SortingBox/style.ts
  components/category/SortingBtn/index.tsx
  components/category/SortingBtn/style.ts
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/SmallNavBar/index.tsx
  components/main/LectureCategory/Category/style.ts
  components/main/LectureCategory/index.tsx
  components/main/MainReport/ReportSection/style.ts
  components/main/MainReport/index.tsx
  components/main/MainReport/style.ts
  components/main/MainReview/Review/style.ts
  components/process/CardTitle/style.ts
  components/process/Title/index.tsx
  components/process/Title/style.ts
  components/process/TypeButton/style.ts
  components/request/RequestLecture/Email/style.ts
  components/request/RequestLecture/LectureCategory/index.tsx
  components/request/RequestLecture/LectureCategory/style.ts
  components/request/RequestLecture/LectureType/style.ts
  components/result/Question/QuestionModal/DropdownInput/style.ts
  components/result/Question/QuestionModal/InputForm/style.ts
  components/result/Question/QuestionModal/QuestionReported/style.ts
  components/result/Question/QuestionModal/index.tsx
  components/result/Question/QuestionModal/style.ts
  components/result/ResultShareButton/style.ts
  package-lock.json
  pages/processPrice/index.tsx
  pages/processTag/index.tsx
  pages/processTime/index.tsx
  pages/result/[id].tsx
  public/assets/icons/index.ts
  public/assets/icons/loadingIconMobile.svg
  public/assets/icons/processPrev.svg
  public/assets/images/ic_developer.png
  public/assets/images/index.ts
  styles/colors.ts
Labels: bug :bug:, 기능구현🎃, 배포 :relaxed:, 이슈해결💟

#155 Feature/category and skill
  components/category/CategoryAndSkillList/CategoryList/index.tsx
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/MobileModal/style.ts
Labels: bug :bug:, style:tulip:

#153 배포 ^_^
  components/category/CategoryAndSkillList/CategoryList/index.tsx
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/MobileModal/style.ts
  components/main/MainReview/Review/style.ts
  components/main/MainReview/style.ts
  components/request/RequestLecture/Email/style.ts
  components/request/RequestLecture/LectureType/style.ts
  public/assets/images/mainReviewBackground-mobile.png
Labels: 배포 :relaxed:

#164 Feature/category and skill
  components/category/CategoryAndSkillList/MobileModal/style.ts
  components/category/CategoryAndSkillList/index.tsx
  components/main/LectureCategory/index.tsx
  pages/category/index.tsx
Labels: bug :bug:, 이슈해결💟

#166 이슈해결 배포
  components/category/CategoryAndSkillList/MobileModal/style.ts
  components/category/CategoryAndSkillList/index.tsx
  components/main/LectureCategory/index.tsx
  pages/category/index.tsx
Labels: bug :bug:, 이슈해결💟

#123 feat: 메타태그 추가
  pages/_app.tsx
  public/assets/icons/metaLogo.png
Labels: seo :ocean:

#163 Feature/nav bar
  components/category/RedirectProcessButton/style.ts
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/LargeNavBar/style.ts
  components/common/NavBar/SmallNavBar/index.tsx
  styles/GlobalStyles.ts
Labels: style:tulip:, 이슈해결💟

#160 이메일 창 width 넓히기
  components/request/RequestLecture/Email/style.ts
Labels: style:tulip:

#162 Feature/main review
  components/main/MainReview/Review/index.tsx
  components/main/MainReview/Review/style.ts
  public/assets/images/mainReviewBackground.png
  public/assets/images/mainReviewProfile1.svg
  public/assets/images/mainReviewProfile2.svg
  public/assets/images/mainReviewProfile3.svg
  public/assets/images/mainReviewProfile4.svg
  public/assets/images/mainReviewProfile5.svg
  public/assets/images/mainReviewProfile6.svg
Labels: 사소하지만중요해🧶

#158 Feature/category list
  components/category/CardBox/LargeCardBox/index.tsx
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardListContainer/style.ts
  pages/category/index.tsx
  store/state.ts
Labels: style:tulip:, 리팩토링 :rabbit:, 이슈해결💟

#167 Feature/settings
  styles/GlobalStyles.ts
Labels: style:tulip:, layout:ice_cube:

#173 Feature/category and skill
  components/category/CategoryAndSkillList/DesktopCategoryAndSkillList/index.tsx
  components/category/CategoryAndSkillList/DesktopCategoryAndSkillList/style.ts
  public/assets/icons/categoryRightArrowIcon.svg
  public/assets/icons/index.ts
  public/assets/icons/redirectRequestArrowIcon.svg
Labels: style:tulip:

#169 Feature/main banner
  components/main/Banner/index.tsx
  components/main/Banner/style.ts
  public/assets/images/mainBannerCompass.png
Labels: style:tulip:

#171 Feature/main lecture category
  components/main/LectureCategory/Category/style.ts
  public/assets/images/index.ts
  public/assets/images/mainLectureCategoryDataIcon.png
  public/assets/images/mainLectureCategoryDesignIcon.png
  public/assets/images/mainLectureCategoryDevIcon.png
  public/assets/images/mainLectureCategoryDevelopIcon.png
  public/assets/images/mainLectureCategoryEtcIcon.png
  public/assets/images/mainLectureCategoryMarketingIcon.png
  public/assets/images/mainLectureCategoryPlanIcon.png
Labels: style:tulip:

#174 Feature/result card
  components/result/ProcessResult/ResultCard/index.tsx
  components/result/ProcessResult/ResultCard/style.ts
  public/assets/icons/index.ts
  public/assets/icons/leftArrowIcon.svg
  public/assets/icons/resultCardLeftArrowIcon.svg
Labels: style:tulip:

#175 Feature/result share
  components/result/ResultShareButton/index.tsx
  components/result/ResultShareButton/style.ts
  public/assets/icons/index.ts
  public/assets/icons/mobileResultShareIcon.svg
  public/assets/icons/resultShareIcon.svg
Labels: style:tulip:

#176 Feature/result question
  components/result/Question/QuestionModal/DropdownInput/index.tsx
  components/result/Question/QuestionModal/DropdownInput/style.ts
  components/result/Question/QuestionModal/InputForm/style.ts
  components/result/Question/QuestionModal/index.tsx
  components/result/Question/QuestionModal/style.ts
  public/assets/icons/desktopDownArrowIcon.svg
  public/assets/icons/desktopQuestionDropdownIcon.svg
  public/assets/icons/desktopUpArrowIcon.svg
  public/assets/icons/index.ts
  public/assets/icons/mobileQuestionDropdownIcon.svg
  public/assets/icons/mobileQuestionModalXIcon.svg
  public/assets/icons/mobileResultDropupIcon.svg
  public/assets/icons/questionModalXIcon.svg
Labels: style:tulip:

#177 refactor: 이미지 리사이징 및 태그 추가
  components/request/RequestCurrentLecture/CurrentLecture/style.ts
  components/request/RequestLecture/LectureCategory/index.tsx
  components/request/RequestLecture/LectureCategory/style.ts
  public/assets/icons/dropdown.svg
  public/assets/images/requestCurrentLectureBackground1.png
  public/assets/images/requestCurrentLectureBackground2.png
  public/assets/images/requestCurrentLectureBackground3.png
  public/assets/images/requestCurrentLectureBackground4.png
Labels: style:tulip:, 사소하지만중요해🧶

#178 Feature/request week rank
  components/request/RequestWeeklyRank/index.tsx
  public/assets/icons/requestRankLine.svg
Labels: 사소하지만중요해🧶

#172 Feature/category list
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardListContainer/index.tsx
  components/category/CardListContainer/style.ts
  components/category/SortingBox/index.tsx
  components/category/SortingBtn/index.tsx
  components/main/Footer/style.ts
  components/main/LectureCategory/index.tsx
  pages/category/index.tsx
  public/assets/icons/arrowDown.svg
  public/assets/icons/arrowRight.svg
  public/assets/images/categoryClickImg.png
Labels: 사소하지만중요해🧶, 리팩토링 :rabbit:

#181 Settings
  components/common/Modal/style.ts
  components/main/MainReport/style.ts
Labels: style:tulip:, layout:ice_cube:

#182 Refactor/process resizing
  components/common/Modal/style.ts
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/SmallNavBar/index.tsx
  components/main/Share/style.ts
  components/process/TagButton/style.ts
  components/process/Title/style.ts
  components/process/TypeButton/style.ts
  pages/processPrice/index.tsx
  pages/processTag/index.tsx
  pages/processTime/index.tsx
  public/assets/icons/nextArrowAble.svg
  public/assets/icons/nextArrowDisabled.svg
  public/assets/icons/processPlayIcon.png
  public/assets/icons/processPrev.svg
  public/assets/icons/progressPrice.svg
  public/assets/icons/progressTag.svg
  public/assets/icons/progressTime.svg
Labels: style:tulip:, 리팩토링 :rabbit:

#186 style: 단위 수정
  components/request/RequestBanner/style.ts
Labels: style:tulip:

#187 Feature/request current lecture
  components/request/RequestCurrentLecture/CurrentLecture/style.ts
  components/request/RequestCurrentLecture/index.tsx
  components/request/RequestCurrentLecture/style.ts
Labels: style:tulip:

#188 Feature/main report
  components/main/MainReport/ReportSection/style.ts
  components/main/MainReport/style.ts
Labels: style:tulip:

#189 Feature/main review
  components/main/MainReview/Review/style.ts
  components/main/MainReview/style.ts
Labels: style:tulip:
