Repository TeamGrowTo/Team-GrowTo-Client, pull requests merged in 2022-03, with the labels that each got.

#203 Feature/result card
  components/result/ProcessResult/index.tsx
Labels: UX writing :writing_hand:

#206 Feature/result question
  components/result/Question/QuestionModal/DropdownInput/index.tsx
  components/result/Question/QuestionModal/DropdownInput/style.ts
Labels: 이슈해결💟

#207 Feature/result share
  components/result/ResultShareButton/index.tsx
Labels: UX writing :writing_hand:

#208 Feature/redirect process page
  components/category/RedirectProcessButton/index.tsx
Labels: UX writing :writing_hand:

#209 Feature/result notification
  components/result/MiddleNotification/index.tsx
Labels: UX writing :writing_hand:

#210 Feature/main lecture category
  components/main/LectureCategory/index.tsx
Labels: UX writing :writing_hand:

#213 chore: UX writing 반영
  components/request/RequestBanner/index.tsx
  components/request/RequestBanner/style.ts
  components/request/RequestCurrentLecture/CurrentLecture/style.ts
  components/request/RequestCurrentLecture/index.tsx
  components/request/RequestCurrentLecture/style.ts
  components/request/RequestLecture/Email/style.ts
  components/request/RequestLecture/LectureCategory/style.ts
  components/request/RequestLecture/LectureType/style.ts
  components/request/RequestLecture/style.ts
  components/request/RequestWeeklyRank/Rank/style.ts
  components/request/RequestWeeklyRank/index.tsx
  components/request/RequestWeeklyRank/style.ts
Labels: UX writing :writing_hand:

#212 chore: UX writing 반영
  components/main/MainReview/index.tsx
Labels: UX writing :writing_hand:

#216 fix: 요소 리사이징
  components/main/MainReview/Review/style.ts
  components/main/MainReview/style.ts
Labels: style:tulip:, UX writing :writing_hand:

#215 fix: 요소 리사이징
  components/main/MainReport/ReportSection/style.ts
  components/main/MainReport/style.ts
Labels: style:tulip:, UX writing :writing_hand:

#204 Feature/category and skill
  components/category/CategoryAndSkillList/CategoryList/index.tsx
  components/category/CategoryAndSkillList/CategoryList/style.ts
  components/category/CategoryAndSkillList/DesktopCategoryAndSkillList/index.tsx
  components/category/CategoryAndSkillList/MobileCategoryAndSkill/index.tsx
  components/category/CategoryAndSkillList/MobileModal/index.tsx
  components/category/CategoryAndSkillList/SkillList/index.tsx
  components/category/CategoryAndSkillList/SkillList/style.ts
  components/common/NavBar/SmallNavBar/style.ts
  pages/category/index.tsx
Labels: style:tulip:, 이슈해결💟, UX writing :writing_hand:

#214 Feature/main banner
  components/main/Banner/index.tsx
  components/main/Banner/style.ts
Labels: UX writing :writing_hand:

#218 categoryList, result
  components/category/CardListContainer/style.ts
  components/category/Result/index.tsx
  pages/result/[id].tsx
Labels: UX writing :writing_hand:

#220 fix: introduce 너비 수정
  components/main/MainReview/Review/style.ts
Labels: style:tulip:

#221 배포
  components/category/CardListContainer/style.ts
  components/category/Result/index.tsx
  components/main/Footer/index.tsx
  components/main/MainReview/Review/style.ts
  pages/result/[id].tsx
Labels: 배포 :relaxed:

#223 Feature/result question
  components/result/Question/QuestionModal/index.tsx
  hooks/UseRegex.ts
Labels: 기능구현🎃, 리팩토링 :rabbit:

#226 fix: 모바일 화면 크기 해결
  components/main/MainReview/Review/style.ts
Labels: 배포 :relaxed:, 반응형💫

#227 Settings
  components/main/MainReport/style.ts
Labels: bug :bug:

#233 Feature/request lecture
  components/request/RequestLecture/EmailInput/index.tsx
  components/request/RequestLecture/EmailInput/style.ts
  components/request/RequestLecture/LectureCategoryInput/index.tsx
  components/request/RequestLecture/LectureCategoryInput/style.ts
  components/request/RequestLecture/LectureTypeInput/index.tsx
  components/request/RequestLecture/LectureTypeInput/style.ts
  components/request/RequestLecture/index.tsx
  public/assets/images/requestCurrentLectureBackground1.png
  public/assets/images/requestCurrentLectureBackground2.png
  public/assets/images/requestCurrentLectureBackground3.png
  public/assets/images/requestCurrentLectureBackground4.png
Labels: 기능구현🎃

#228 Feature/result question
  components/result/Question/QuestionModal/style.ts
  components/result/Question/style.ts
Labels: bug :bug:, style:tulip:

#234 Feature/category and skill
  components/category/CategoryAndSkillList/SkillList/style.ts
Labels: bug :bug:, style:tulip:

#235 Feature/main banner
  components/main/Banner/index.tsx
  components/main/Banner/style.ts
Labels: bug :bug:, UX writing :writing_hand:

#236 fix: UX writing 변경으로 글자 밀림 해결
  components/result/ProcessResult/index.tsx
  components/result/ProcessResult/style.ts
Labels: bug :bug:, style:tulip:, UX writing :writing_hand:

#238 Feature/nav bar
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/LargeNavBar/style.ts
  components/common/NavBar/SmallNavBar/index.tsx
  components/common/NavBar/SmallNavBar/style.ts
Labels: 기능구현🎃, 모바일 :hamburger:

#239 Feature/result card
  components/result/ProcessResult/style.ts
Labels: bug :bug:, UX writing :writing_hand:

#237 배포
  components/category/CategoryAndSkillList/SkillList/style.ts
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/LargeNavBar/style.ts
  components/common/NavBar/SmallNavBar/index.tsx
  components/common/NavBar/SmallNavBar/style.ts
  components/main/Banner/index.tsx
  components/main/Banner/style.ts
  components/main/MainReport/style.ts
  components/request/RequestLecture/EmailInput/index.tsx
  components/request/RequestLecture/EmailInput/style.ts
  components/request/RequestLecture/LectureCategoryInput/index.tsx
  components/request/RequestLecture/LectureCategoryInput/style.ts
  components/request/RequestLecture/LectureTypeInput/index.tsx
  components/request/RequestLecture/LectureTypeInput/style.ts
  components/request/RequestLecture/index.tsx
  components/result/ProcessResult/index.tsx
  components/result/ProcessResult/style.ts
  components/result/Question/QuestionModal/style.ts
  components/result/Question/style.ts
  public/assets/images/requestCurrentLectureBackground1.png
  public/assets/images/requestCurrentLectureBackground2.png
  public/assets/images/requestCurrentLectureBackground3.png
  public/assets/images/requestCurrentLectureBackground4.png
Labels: bug :bug:, 배포 :relaxed:, 이슈해결💟, UX writing :writing_hand:

#240 Feature/common modal
  components/common/Modal/style.ts
Labels: bug :bug:

#244 배포
  public/sitemap.xml
  scripts/sitemapCommon.mjs
Labels: documentation :scroll:

#245 배포
  public/sitemap.xml
  scripts/sitemapCommon.mjs
Labels: documentation :scroll:

#247 Settings
  public/sitemap.xml
  scripts/sitemapCommon.mjs
Labels: bug :bug:, documentation :scroll:

#248 배포
  public/sitemap.xml
  scripts/sitemapCommon.mjs
Labels: bug :bug:, documentation :scroll:, 배포 :relaxed:

#246 Feature/category list
  apis/lectures.api.ts
  components/category/CardBox/LargeCardBox/index.tsx
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/index.tsx
  components/category/CardBox/SmallCardBox/style.ts
  components/category/SortingBox/index.tsx
  store/state.ts
  types/info.type.ts
Labels: 기능구현🎃, style:tulip:, 이슈해결💟
