Repository TeamGrowTo/Team-GrowTo-Client, pull requests merged in 2022-05, with the labels that each got.

#257 Feature/main banner
  components/main/Banner/AutoImageSlider/NextArrow/index.tsx
  components/main/Banner/AutoImageSlider/NextArrow/style.ts
  components/main/Banner/AutoImageSlider/PrevArrow/index.tsx
  components/main/Banner/AutoImageSlider/PrevArrow/style.ts
  components/main/Banner/AutoImageSlider/SlideIndexView/index.tsx
  components/main/Banner/AutoImageSlider/SlideIndexView/style.ts
  components/main/Banner/AutoImageSlider/index.tsx
  components/main/Banner/AutoImageSlider/style.ts
  components/main/Banner/FirstBanner/index.tsx
  components/main/Banner/FirstBanner/style.ts
  components/main/Banner/SecondBanner/index.tsx
  components/main/Banner/SecondBanner/style.ts
  components/main/Banner/ThirdBanner/index.tsx
  components/main/Banner/ThirdBanner/style.ts
  components/main/Banner/index.tsx
  package-lock.json
  package.json
Labels: 기능구현🎃, style:tulip:

#263 Feature/main lecture category
  components/main/LectureCategory/Category/style.ts
  components/main/LectureCategory/CategoryList/index.tsx
  components/main/LectureCategory/CategoryList/style.ts
  components/main/LectureCategory/style.ts
Labels: style:tulip:

#268 Feature/process0
  .env
  components/common/Layout.tsx
  components/main/MainToProcessButton/index.tsx
  components/process/CategoryButton/index.tsx
  components/process/CategoryButton/style.ts
  components/process/CategoryList/index.tsx
  components/process/CategoryList/style.ts
  components/process/SkillList/index.tsx
  components/process/SkillList/style.ts
  components/process/Title/index.tsx
  pages/process/index.tsx
  public/assets/icons/ic_data.png
  public/assets/icons/ic_design.png
  public/assets/icons/ic_developer.png
  public/assets/icons/ic_etc.png
  public/assets/icons/ic_marketing.png
  public/assets/icons/ic_plan.png
  public/assets/icons/index.ts
Labels: 기능구현🎃

#267 강의 리스트 제목 4줄 이상 자르기 수정
  components/category/CardBox/LargeCardBox/index.tsx
  components/category/CardBox/LargeCardBox/style.ts
Labels: 이슈해결💟

#262 Feature/result card
  apis/lectures.api.ts
  components/result/ProcessResult/ProcessResultSubTitle/index.tsx
  components/result/ProcessResult/ProcessResultSubTitle/style.ts
  components/result/ProcessResult/ResultCard/BottomButtons/index.tsx
  components/result/ProcessResult/ResultCard/BottomButtons/style.ts
  components/result/ProcessResult/ResultCard/Info/style.ts
  components/result/ProcessResult/ResultCard/index.tsx
  components/result/ProcessResult/ResultCard/style.ts
  components/result/ProcessResult/index.tsx
  components/result/ProcessResult/style.ts
  pages/result/[id].tsx
  public/assets/icons/mobileResultCardRightArrowIcon.svg
  types/lectures.type.ts
Labels: style:tulip:

#266 Feature/main lecture category
  components/main/LectureCategory/CategoryList/style.ts
Labels: style:tulip:

#261 Feature/redirect process page
  components/category/RedirectProcessButton/DesktopToProcessButton/index.tsx
  components/category/RedirectProcessButton/DesktopToProcessButton/style.ts
  components/category/RedirectProcessButton/MobileToProcessButton/index.tsx
  components/category/RedirectProcessButton/MobileToProcessButton/style.ts
  components/category/RedirectProcessButton/index.tsx
  components/category/RedirectProcessButton/style.ts
  pages/category/index.tsx
  public/assets/icons/10second.svg
  public/assets/icons/categoryReduceIcon.png
  public/assets/icons/categoryToProcessIcon.png
  public/assets/icons/icRight.svg
  public/assets/icons/icRightSmall.svg
  public/assets/icons/index.ts
Labels: style:tulip:

#270 Feature/result card
  components/result/ProcessResult/ResultCard/Tags/index.tsx
Labels: style:tulip:

#272 Feature/main banner
  components/main/Banner/AutoImageSlider/NextArrow/index.tsx
  components/main/Banner/AutoImageSlider/NextArrow/style.ts
  components/main/Banner/AutoImageSlider/PrevArrow/index.tsx
  components/main/Banner/AutoImageSlider/PrevArrow/style.ts
  components/main/Banner/AutoImageSlider/SlideIndexView/style.ts
  components/main/Banner/AutoImageSlider/index.tsx
  components/main/Banner/AutoImageSlider/style.ts
  public/assets/images/mainBannerCompass.png
Labels: bug :bug:, style:tulip:

#275 Feature/main to process
  components/main/MainToProcessButton/ProcessButtonDescription/index.tsx
  components/main/MainToProcessButton/ProcessButtonDescription/style.ts
  components/main/MainToProcessButton/index.tsx
  components/main/MainToProcessButton/style.ts
Labels: style:tulip:, 리팩토링 :rabbit:

#273 Feature/process0
  components/process/CategoryButton/style.ts
  components/process/CategoryList/index.tsx
  components/process/CategoryList/style.ts
  components/process/SkillList/style.ts
  pages/process/index.tsx
Labels: 기능구현🎃, 모바일 :hamburger:

#274 Feature/main to
  components/main/MainTo/index.tsx
  components/main/MainTo/style.ts
  pages/index.tsx
  public/assets/images/arrowToCircle.png
  public/assets/images/graph.png
  public/assets/images/ic_eye.png
  public/assets/images/ic_recommend.png
  public/assets/images/ic_zoom.png
  public/assets/images/index.ts
  public/assets/images/mainCircle.png
  public/assets/images/mainResultCard.png
  public/assets/images/nextArrow.png
Labels: 기능구현🎃, 모바일 :hamburger:

#253 fix: CurrentLecture Background 이미지 수정
  components/request/RequestCurrentLecture/CurrentLecture/style.ts
  public/assets/images/requestBannerBackground-mobile.png
  public/assets/images/requestBannerBackground.png
  public/assets/images/requestCurrentBackground1.png
  public/assets/images/requestCurrentBackground2.png
  public/assets/images/requestCurrentBackground3.png
  public/assets/images/requestCurrentBackground4.png
  public/assets/images/requestCurrentBackground5.png
  public/assets/images/requestCurrentBackground6.png
  public/assets/images/requestCurrentLectureBackground1.png
  public/assets/images/requestCurrentLectureBackground2.png
  public/assets/images/requestCurrentLectureBackground3.png
  public/assets/images/requestCurrentLectureBackground4.png
Labels: style:tulip:, UX writing :writing_hand:

#271 main페이지 our mission섹션
  components/main/Share/index.tsx
  components/main/Share/style.ts
  pages/index.tsx
  public/assets/fonts/Poppins-Bold.ttf
  public/assets/fonts/Poppins-Bold.woff
  public/assets/fonts/Poppins-Bold.woff2
  public/assets/fonts/font.css
  public/assets/images/index.ts
  public/assets/images/mainMissionBackground.png
Labels: 기능구현🎃, style:tulip:, 반응형💫, UX writing :writing_hand:

#276 Feature/main to
  components/main/MainTo/style.ts
  components/process/CategoryList/style.ts
  pages/process/index.tsx
Labels: bug :bug:

#277 Refactor/refactoring
  components/main/Banner/index.tsx
  components/process/CategoryList/index.tsx
  components/result/MiddleNotification/index.tsx
  components/result/ProcessResult/ResultCard/index.tsx
  components/result/ResultShareButton/index.tsx
  pages/result/[id].tsx
Labels: 리팩토링 :rabbit:

#280 fix: gtag수정
  libs/gtag.ts
Labels: seo :ocean:

#284 Feature/main banner
  components/main/Banner/FirstBanner/index.tsx
  components/main/Banner/FirstBanner/style.ts
  components/main/Banner/SecondBanner/index.tsx
  components/main/Banner/SecondBanner/style.ts
  public/assets/images/index.ts
  public/assets/images/mobileMainBannerCompass.png
  public/assets/images/mobileMainBannerCustomLecture.png
Labels: style:tulip:, 모바일 :hamburger:

#285 Feature/main to process
  components/main/MainToProcessButton/style.ts
Labels: style:tulip:

#287 맞춤강의 네비게이션 바 메뉴에 추가
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/SmallNavBar/index.tsx
  components/common/NavBar/SmallNavBar/style.ts
Labels: 기능구현🎃, 모바일 :hamburger:, 이슈해결💟

#288 메인 'our mission'
  components/main/Share/index.tsx
  components/main/Share/style.ts
Labels: 사소하지만중요해🧶

#286 category, result 정렬버튼과 결과 메시지
  components/category/CardListContainer/style.ts
  components/category/Result/index.tsx
  components/category/Result/style.ts
  components/category/SortingBox/index.tsx
  components/category/SortingBox/style.ts
  pages/category/index.tsx
  store/state.ts
  styles/colors.ts
Labels: 반응형💫, 모바일 :hamburger:, 이슈해결💟, UX writing :writing_hand:

#289 0511QA반영 배포
  components/category/CardListContainer/style.ts
  components/category/Result/index.tsx
  components/category/Result/style.ts
  components/category/SortingBox/index.tsx
  components/category/SortingBox/style.ts
  components/common/NavBar/LargeNavBar/index.tsx
  components/common/NavBar/SmallNavBar/index.tsx
  components/common/NavBar/SmallNavBar/style.ts
  components/main/Banner/FirstBanner/index.tsx
  components/main/Banner/FirstBanner/style.ts
  components/main/Banner/SecondBanner/index.tsx
  components/main/Banner/SecondBanner/style.ts
  components/main/MainToProcessButton/style.ts
  components/main/Share/index.tsx
  components/main/Share/style.ts
  pages/category/index.tsx
  public/assets/images/index.ts
  public/assets/images/mobileMainBannerCompass.png
  public/assets/images/mobileMainBannerCustomLecture.png
  store/state.ts
  styles/colors.ts
Labels: 배포 :relaxed:

#290 feat: mobile 정렬 및 구조 수정, 컴포넌트 이름수정
  components/main/Footer/index.tsx
  components/main/Footer/style.ts
Labels: 사소하지만중요해🧶, 모바일 :hamburger:, 이슈해결💟

#292 강의 카드 클릭영역 재설정
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/index.tsx
  components/category/CardBox/SmallCardBox/style.ts
Labels: 모바일 :hamburger:, 이슈해결💟

#293 0524 issue 반영
  components/category/CardBox/LargeCardBox/style.ts
  components/category/CardBox/SmallCardBox/index.tsx
  components/category/CardBox/SmallCardBox/style.ts
  components/main/Footer/index.tsx
  components/main/Footer/style.ts
Labels: 배포 :relaxed:
